/*
 * Module name:  ws_ui_inexus
 * Copyright (C) 2025 北京普析通用仪器有限责任公司 All Rights Reserved.
 * 此源代码仅限在公司内部使用。未经公司事先书面许可，任何单位和个人不得以任何方式复制、传播本代码的任何部分。
 * Description:
 */

/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EchartsBar: typeof import('./src/components/echartsBar/index.vue')['default']
    EchartsHorizontalBar: typeof import('./src/components/echartsHorizontalBar/index.vue')['default']
    EchartsLine: typeof import('./src/components/EchartsLine/index.vue')['default']
    EchartsRose: typeof import('./src/components/echartsRose/index.vue')['default']
    HeadTitle: typeof import('./src/components/headTitle/index.vue')['default']
    ImportModal: typeof import('./src/components/importModal/index.vue')['default']
    LeftCollapsePanel: typeof import('./src/components/leftCollapsePanel/index.vue')['default']
    LineChart: typeof import('./src/components/lineChart/index.vue')['default']
    MathJax: typeof import('./src/components/MathJax/index.vue')['default']
    MathQuillEditor: typeof import('./src/components/mathQuillEditor/index.vue')['default']
    ReportContent: typeof import('./src/components/reportContent/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadFile: typeof import('./src/components/uploadFile/index.vue')['default']
    Uv3DColumnChart: typeof import('./src/components/uv3DColumnChart/index.vue')['default']
    Uv3DLineChart: typeof import('./src/components/uv3DLineChart/index.vue')['default']
    Uv3DPieChart: typeof import('./src/components/uv3DPieChart/index.vue')['default']
    UvCollapse: typeof import('./src/components/uvCollapse/index.vue')['default']
    UvCollapseRightSlot: typeof import('./src/components/uvCollapseRightSlot/index.vue')['default']
    UvComplexTables: typeof import('./src/components/uvComplexTables/index.vue')['default']
    UvDescriptions: typeof import('./src/components/uvDescriptions/index.vue')['default']
    UvEditCellTable: typeof import('./src/components/uvEditCellTable/index.vue')['default']
    UvFileInput: typeof import('./src/components/uvFileInput/index.vue')['default']
    UvForm: typeof import('./src/components/uvForm/index.vue')['default']
    UvHasIconBtn: typeof import('./src/components/uvHasIconBtn/index.vue')['default']
    UvLayoutHeader: typeof import('./src/components/uvLayoutHeader/index.vue')['default']
    UvLayoutSideBar: typeof import('./src/components/uvLayoutSideBar/index.vue')['default']
    UvLight: typeof import('./src/components/uvLight/index.vue')['default']
    UvLineHasScatter: typeof import('./src/components/uvLineHasScatter/index.vue')['default']
    UvLinesChart: typeof import('./src/components/uvLinesChart/index.vue')['default']
    UvMathAliveField: typeof import('./src/components/uvMathAliveField/index.vue')['default']
    UvModal: typeof import('./src/components/uvModal/index.vue')['default']
    UvOffice: typeof import('./src/components/uvOffice/index.vue')['default']
    UvOfficeDocx: typeof import('./src/components/uvOfficeDocx/index.vue')['default']
    UvOfficeExcel: typeof import('./src/components/uvOfficeExcel/index.vue')['default']
    UvOfficePdf: typeof import('./src/components/uvOfficePdf/index.vue')['default']
    UvSelect: typeof import('./src/components/uvSelect/index.vue')['default']
    UvTable: typeof import('./src/components/uvTable/index.vue')['default']
    UvTags: typeof import('./src/components/uvTags/index.vue')['default']
    UvTagsClickForm: typeof import('./src/components/uvTagsClickForm/index.vue')['default']
    VxeTable: typeof import('./src/components/vxeTable/index.vue')['default']
  }
}
