/*
 * Module name:  ws_ui_inexus
 * Copyright (C) 2025 北京普析通用仪器有限责任公司 All Rights Reserved.
 * 此源代码仅限在公司内部使用。未经公司事先书面许可，任何单位和个人不得以任何方式复制、传播本代码的任何部分。
 * Description:
 */

// 系统角色与菜单之间映射
export const menuConfig = {
  '1': [
    'methodOptimizationHome',
    'instrumentHome',
    'instrumentConfig',
    'autolabConfig',
    'instrumentCalibration',
    'historicalTask',
    'usageStatisticsDetail',
    'historicalTaskDetail',
    'softwareActivation',
    'experimentTest',
    'lumneScence',
    'quantityDetermind',
    'spectralScan',
    'timeScan',
    'twoComponentMeasure',
    'reportDesignHome',
    'reportTemplateDesign',
    'templateEdit',
    'standardTemplateDesign',
    'installTemplateDesign',
    'systemManageHome',
    'panelConfig',
    'manageConfig',
    'databaseConfig',
    'logManage',
    'stepDelete',
    'serviceParameters',
    'standardManageHome',
    'userManageHome',
    'systemUserManage',
    'rightManageHome',
    'userRightManage',
    'catEditUser',
    'productLineManage',

    'prodLineTool',
    'devDebugTool',
    'debugToolHome',

    'factoryInspectionHome',
    'factoryInspectionTemplateManage',
    'unboxingInspectionHome',

    'customerGuide',
    'repairPersonGuide',
    'instrumentMonitor',

    'repairPersonGuide',
    'convenientRepairHome',
    'instrumentMonitor',
    'customerGuide',

    'verificationCalibrationHome',
    'verification',
    'calibration',
    'periodicCheck',

    'noticeManageHome',

    'designPatternHome',
    'partDesign',
    'createPart',
    'modifyPart',
    'processDesign',
    'createProcess',
    'modifyProcess',

    'simpleMode',
    'wizardMode',
    'dataManagement',
    'dataManagementHome',
    'modifyPart',
    'viewHistoryUVWi',
    'projectManagement',
    'taskManagement',
    'methodManagement',
    'wizardModeHome',
    '403',
    '404',
    'welcome',
  ], // 开发人员可见菜单
  '2': [
    'methodOptimizationHome',
    'instrumentHome',
    'instrumentConfig',
    'autolabConfig',
    'instrumentCalibration',
    'historicalTask',
    'usageStatisticsDetail',
    'historicalTaskDetail',
    'softwareActivation',
    'experimentTest',
    'lumneScence',
    'quantityDetermind',
    'spectralScan',
    'timeScan',
    'twoComponentMeasure',
    'reportDesignHome',
    'reportTemplateDesign',
    'templateEdit',
    'standardTemplateDesign',
    'installTemplateDesign',
    'systemManageHome',
    'panelConfig',
    'manageConfig',
    'databaseConfig',
    'logManage',
    'stepDelete',
    'serviceParameters',
    'standardManageHome',
    'userManageHome',
    'systemUserManage',
    'rightManageHome',
    'userRightManage',
    'catEditUser',
    'productLineManage',

    'prodLineTool',
    'devDebugTool',
    'debugToolHome',

    'factoryInspectionHome',
    'factoryInspectionTemplateManage',
    'unboxingInspectionHome',

    'customerGuide',
    'repairPersonGuide',
    'instrumentMonitor',

    'repairPersonGuide',
    'convenientRepairHome',
    'instrumentMonitor',
    'customerGuide',

    'verificationCalibrationHome',
    'verification',
    'calibration',
    'periodicCheck',

    'noticeManageHome',

    'designPatternHome',
    'partDesign',
    'createPart',
    'modifyPart',
    'processDesign',
    'createProcess',
    'modifyProcess',

    'simpleMode',
    'wizardMode',
    'dataManagement',
    'dataManagementHome',
    'modifyPart',
    'viewHistoryUVWi',
    'projectManagement',
    'taskManagement',
    'methodManagement',
    'wizardModeHome',
    '403',
    '404',
    'welcome',
  ], // 产线人员可见菜单
  '3': [
    'methodOptimizationHome',
    'instrumentHome',
    'instrumentConfig',
    'autolabConfig',
    'instrumentCalibration',
    'historicalTask',
    'usageStatisticsDetail',
    'historicalTaskDetail',
    'softwareActivation',
    'experimentTest',
    'lumneScence',
    'quantityDetermind',
    'spectralScan',
    'timeScan',
    'twoComponentMeasure',
    'reportDesignHome',
    'reportTemplateDesign',
    'templateEdit',
    'standardTemplateDesign',
    'installTemplateDesign',
    'systemManageHome',
    'panelConfig',
    'manageConfig',
    'databaseConfig',
    'logManage',
    'stepDelete',
    'serviceParameters',
    'standardManageHome',
    'userManageHome',
    'productLineManage',
    'userRightManage',
    'catEditUser',
    '403',
    '404',
    'welcome',
  ], // 维修人员可见菜单
  '4': [
    'methodOptimizationHome',
    'instrumentHome',
    'instrumentConfig',
    'autolabConfig',
    'instrumentCalibration',
    'historicalTask',
    'usageStatisticsDetail',
    'historicalTaskDetail',
    'softwareActivation',
    'experimentTest',
    'lumneScence',
    'quantityDetermind',
    'spectralScan',
    'timeScan',
    'twoComponentMeasure',
    'reportDesignHome',
    'reportTemplateDesign',
    'templateEdit',
    'standardTemplateDesign',
    'installTemplateDesign',
    'systemManageHome',
    'panelConfig',
    'manageConfig',
    'databaseConfig',
    'logManage',
    'stepDelete',
    'serviceParameters',
    'standardManageHome',
    'userManageHome',
    'productLineManage',
    'userRightManage',
    'catEditUser',
    '403',
    '404',
    'welcome',
  ], // 客户人员可见菜单
}
